#spring.datasource.url=jdbc:postgresql://localhost:5432/Endearments?currentSchema=public
##spring.datasource.url=jdbc:sqlserver://192.168.3.18:1433;databaseName=Endearments;encrypt=false
#spring.datasource.username=postgres
#spring.datasource.password=M!r@boT3ch
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#jwt.secret-key=l1nvjHby8fS/s8tUesMLluvEWYvOdbDPSgQQTZp+J9461UHfVvGjVq60Kio7JGk3HHQaOIWQxQGsxTlDo23NLA==
#jwt.refresh-key=rcAeksjUacMT8+AzIl16PMvQCl4GvoG+L5rzO3br4bXrUWqoc+/johjHNmVEQLl/pstc2+5iIiqIMHnWyeYbQg==
#jwt.access-expiration=900000
#jwt.refresh-expiration=604800000
#jwt.reset-expiration=900000
#
#spring.flyway.enabled=false
#spring.flyway.locations=classpath:db/migration
#
#spring.data.redis.host=127.0.0.1
#spring.data.redis.port=6379
#cloudinary.cloud_name=djs09mhzd
#cloudinary.api_key=164251279167763
#cloudinary.api_secret=mSRQ566hrM4Pvar3WnE-Q2hwpsk
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=daopta@mirabo-tech.com
#spring.mail.password=jdnxupamzrgcwshv
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
#async.executor.core-pool-size=4
#async.executor.max-pool-size=8
#async.executor.queue-capacity=50
#
#logging.level.org.hibernate=DEBUG
spring.datasource.url=jdbc:postgresql://localhost:5432/Endearments?currentSchema=dbo
#spring.datasource.url=jdbc:sqlserver://192.168.3.18:1433;databaseName=Endearments;encrypt=false
spring.datasource.username=sa
spring.datasource.password=M!r@boT3ch
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret-key=l1nvjHby8fS/s8tUesMLluvEWYvOdbDPSgQQTZp+J9461UHfVvGjVq60Kio7JGk3HHQaOIWQxQGsxTlDo23NLA==
jwt.refresh-key=rcAeksjUacMT8+AzIl16PMvQCl4GvoG+L5rzO3br4bXrUWqoc+/johjHNmVEQLl/pstc2+5iIiqIMHnWyeYbQg==
jwt.access-expiration=900000
jwt.refresh-expiration=604800000
jwt.reset-expiration=900000
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
#
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

cloudinary.cloud_name=djs09mhzd
cloudinary.api_key=164251279167763
cloudinary.api_secret=mSRQ566hrM4Pvar3WnE-Q2hwpsk

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=daopta@mirabo-tech.com
spring.mail.password=jdnxupamzrgcwshv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

async.core-pool-size=4
async.max-pool-size=8
async.queue-capacity=50
logging.level.org.hibernate=info
