version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_dev
#    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: M!r@boT3ch
      POSTGRES_DB: Endearments
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_dev
#    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
  redis_data_dev:
